# Generated by Django 4.2.2 on 2023-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_show_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
