# Generated by Django 4.2.2 on 2023-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_show_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='stillWatching',
            field=models.BooleanField(verbose_name='Still watching?'),
        ),
    ]
