# Generated by Django 4.2.2 on 2023-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_show_stillwatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='photo',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
