# Generated by Django 4.2.2 on 2023-06-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_show_photo_show_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL link:'),
        ),
    ]
