# Generated by Django 4.2.2 on 2023-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_show_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
